version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: carrierwave
    versions:
    - 1.3.2
    - 2.1.1
    - 2.2.0
  - dependency-name: rails_admin
    versions:
    - 1.4.3
    - 2.0.2
  - dependency-name: omniauth
    versions:
    - 1.9.1
    - 2.0.0
  - dependency-name: database_cleaner
    versions:
    - 1.8.5
    - 2.0.0
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: ffi
    versions:
    - 1.14.2
