language: ruby
rvm:
 - 2.3.1
cache: bundler
before_install:
  - gem update --system
  - gem --version
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare

